### ISSUE TITLE
Unable to register to NetManager. Invalid subnetwork received

### ISSUE THREAD

**Issue by lucamarchiori** [oakestra/oakestra-net#190]
## Short
The NetManager and the NodeEngine crash.

## Proposal 
Both the NetManager and the NodeEngine in use are from the dev branch.

**NetManager execution:**
```
lucam@ubuntuserver:~/oakestra-net/node-net-manager/build$ sudo NetManager -p 6000
2024/10/15 14:12:35 {192.168.1.95 50103 192.168.1.95 10003}
2024/10/15 14:12:35 NetManager started. Waiting for registration.
2024/10/15 14:12:38 Received HTTP request - /register 
2024/10/15 14:12:38 {670e2fc4eccad2d1ecedf8bd}
INFO-2024/10/15 14:12:38 ProxySetup.go:46: Utilizing config: {goProxyTun 10.30.0.0 255.255.0.0 10.19.1.254 50103 1450 fcef::dead:beef fcef:: 21}
2024/10/15 14:12:38 Connected to the MQTT broker
2024/10/15 14:12:38 Subscribed to topics 
INFO-2024/10/15 14:12:38 ProxySetup.go:124: Bringing tun up with addr 10.19.1.254/12
INFO-2024/10/15 14:12:38 ProxySetup.go:126: 
INFO-2024/10/15 14:12:38 ProxySetup.go:131: Bringing tun up with IPv6 addr fcef::dead:beef/7
INFO-2024/10/15 14:12:38 ProxySetup.go:144: Disabling tun dev reverse path filtering
INFO-2024/10/15 14:12:38 ProxySetup.go:152: Changing TUN's MTU
INFO-2024/10/15 14:12:38 ProxySetup.go:160: adding routing rule for 10.30.0.0/16 to goProxyTun
INFO-2024/10/15 14:12:38 ProxySetup.go:165: adding routing rule for fcef:: to goProxyTun
INFO-2024/10/15 14:12:38 ProxySetup.go:170: adding firewall rule goProxyTun
2024/10/15 14:12:38 Local Interface in use:  enp1s0  with addr  192.168.1.95
INFO-2024/10/15 14:12:38 ProxySetup.go:89: Created ProxyTun device: goProxyTun
INFO-2024/10/15 14:12:38 ProxySetup.go:90: Local Ip detected: 192.168.1.95
INFO-2024/10/15 14:12:38 ProxySetup.go:106: Starting proxy listening mode
INFO-2024/10/15 14:12:38 EnvironmentManager.go:141: Asking the cluster for a new subnetwork
INFO-2024/10/15 14:12:38 ProxyTunnel.go:265: GoProxyTunnel outgoing listening started
INFO-2024/10/15 14:12:38 ProxyTunnel.go:295: GoProxyTunnel ingoing listening started
ERROR-2024/10/15 14:12:38 v6Packet.go:96: Could not determine TransportLayer of IPv6 Packet.
ERROR-2024/10/15 14:12:42 v6Packet.go:96: Could not determine TransportLayer of IPv6 Packet.
2024/10/15 14:12:48 TIMEOUT - Table query without response, quitting goroutine
2024/10/15 14:12:48 Invalid subnetwork received. Can't proceed.
```

**NodeEngine execution:**
```
lucam@ubuntuserver:~/oakestra_fork/oakestra/go_node_engine/build$ sudo ./NodeEngine_amd64 -a 192.168.1.95
INFO-2024/10/15 14:12:38 root.go:96: INIT: Starting handshake with cluster orchestrator 192.168.1.95:10100
INFO-2024/10/15 14:12:38 root.go:98: Node Statistics: 
__________________
INFO-2024/10/15 14:12:38 root.go:99: CPU Cores: 1
INFO-2024/10/15 14:12:38 root.go:100: CPU Usage: 0.430000
INFO-2024/10/15 14:12:38 root.go:101: Mem Usage: 53.498394
INFO-2024/10/15 14:12:38 root.go:102: GPU Driver: -
INFO-2024/10/15 14:12:38 root.go:103: 
________________
INFO-2024/10/15 14:12:38 root.go:105: Got cluster response with MQTT port 10003 and node ID 670e2fc4eccad2d1ecedf8bd
ERROR-2024/10/15 14:12:48 root.go:71: Unable to register to NetManager: Post "http://localhost:6000/register": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

```

## Status
Open problem, i am new to the project and I'd like to contribute but first i need to understand what is happening.

## Solution
- Todo

## Checklist
- [ ] Discussed
- [ ] Solved
- [ ] Tested

**Comment by nitindermohan** [comment]
@lucamarchiori thank you for trying out Oakestra. Could you please share some more information regarding your setup? Specifically:

- Are you planning to build all the components in the same machine? If yes, what configuration are you using?
-  Are you following the steps from the Wiki (https://www.oakestra.io/docs/getstarted/get-started-cluster/). Were you able to build your root and cluster orchestrators?
- Can you post your `/etc/netmanager/netcfg.json`?

Thanks
NM

**Comment by giobart** [comment]
Hello @lucamarchiori, this issue usually happens when either the worker net component cannot communicate with the cluster or the cluster to the root. First of all, are cluster and root on the same node?
Can you post the logs of cluster and root network components?

Respectively run:

`docker logs root_service_manager`

and

`docker logs cluster_service_manager`

On cluster/root orchestrator machine(s)

Thank you lot :)

**Comment by lucamarchiori** [comment]
@nitindermohan @giobart 
> Are you planning to build all the components in the same machine? If yes, what configuration are you using?

Yes, all the components on the same machine:
```
OS: Pop!_OS 22.04 LTS x86_64 
Host: B450 Steel Legend 
Kernel: 6.9.3-76060903-generic 
Shell: zsh 5.8.1 
Resolution: 2560x1080 
DE: GNOME 42.9 
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz 
GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT 
Memory: 5653MiB / 15910MiB 
```

> Are you following the steps from the Wiki (https://www.oakestra.io/docs/getstarted/get-started-cluster/). Were you able to build your root and cluster orchestrators?

Yes, i built both root and cluster orchestrator without problems.

> Can you post your /etc/netmanager/netcfg.json?

In the log above the IP was *.95 but i changed to .*100 so this is the final config.
```
{
  "NodePublicAddress": "192.168.1.100",
  "NodePublicPort": "50103",
  "ClusterUrl": "192.168.1.100",
  "ClusterMqttPort": "10003"
}
```

> Can you post the logs of cluster and root network components?

```
➜  build git:(develop) ✗ docker logs root_service_manager
Server initialized for eventlet.
INFO:engineio.server:Server initialized for eventlet.
2024-10-16 12:56:28,470 - service_manager - INFO - Connecting to mongo...
INFO:service_manager:Connecting to mongo...
INFO:service_manager:Connecting to mongo...
2024-10-16 12:56:28,471 - service_manager - INFO - MONGODB - init mongo
INFO:service_manager:MONGODB - init mongo
INFO:service_manager:MONGODB - init mongo
2024-10-16 12:56:28,472 - root_service_manager - INFO - (1) wsgi starting up on http://[::]:10099
INFO:root_service_manager:(1) wsgi starting up on http://[::]:10099
2024-10-16 13:14:15,779 - root_service_manager - DEBUG - (1) accepted ('::ffff:172.18.0.12', 52540, 0, 0)
DEBUG:root_service_manager:(1) accepted ('::ffff:172.18.0.12', 52540, 0, 0)
2024-10-16 13:14:15,780 - service_manager - INFO - Incoming Request /api/net/cluster
INFO:service_manager:Incoming Request /api/net/cluster
INFO:service_manager:Incoming Request /api/net/cluster
2024-10-16 13:14:15,781 - service_manager - INFO - {'cluster_id': '670fbc276ab9f603ba204113', 'cluster_address': '172.18.0.1', 'cluster_port': 10110}
INFO:service_manager:{'cluster_id': '670fbc276ab9f603ba204113', 'cluster_address': '172.18.0.1', 'cluster_port': 10110}
INFO:service_manager:{'cluster_id': '670fbc276ab9f603ba204113', 'cluster_address': '172.18.0.1', 'cluster_port': 10110}
2024-10-16 13:14:15,794 - root_service_manager - INFO - ::ffff:172.18.0.12 - - [16/Oct/2024 13:14:15] "POST /api/net/cluster HTTP/1.1" 200 158 0.014461
INFO:root_service_manager:::ffff:172.18.0.12 - - [16/Oct/2024 13:14:15] "POST /api/net/cluster HTTP/1.1" 200 158 0.014461

➜  build git:(develop) ✗ docker logs cluster_service_manager
Server initialized for eventlet.
2024-10-16 13:14:15,469 - service_manager - INFO - MONGODB - init mongo
2024-10-16 13:14:15,471 - cluster_service_manager - INFO - (1) wsgi starting up on http://[::]:10110
```

> Thank you lot :)

Thank you! I might participate a little bit to the project as part of my Master Degree Thesis. Maybe we can get in touch when I'll have everything sorted out :)

**Comment by lucamarchiori** [comment]
Update:
By using the branch 181-make-netmanager-systemd-compatible i don't get the problem anymore and i am able to deploy services. Thanks for your help.

**Comment by Mjaethers** [comment]
Hey @lucamarchiori glad to hear that you managed to get it to work!

But in case someone else comes across this issue:
The NodeEngine can be used without the NetManager, if all the components are deployed on the same machine (1-DOC). However, when using it with the NetManager you also have to specify the port of the cluster orchestrator (usually 10100) and the port of the NetManager (usually 6000, but you specify it when launching the NetManager with the -p flag).

So after starting the NetManager with `sudo NetManager -p 6000` you would have to start the NodeEngine with `sudo NodeEngine -n 6000 -p 10100 -a 192.168.1.95`

I'm still somewhat surprised that you got the error `Invalid subnetwork received. Can't proceed.` as the NetManager should have never received the NodeEngine registration.
If you could spare a few minutes, could you check the environmental variable SYSTEM_MANAGER_URL in the terminal sessions where the root and cluster orchestrators are being run? Make sure it's correctly set to the device IP. Please also make sure that you are only running the NodeEngine once.

If you could let us know if these suggestions allow you to use the NetManager on the develop branch that would be greatly appreciated!

Thanks in advance!

**Comment by giobart** [comment]
@lucamarchiori I'm happy to hear that however I'm not sure if that's a solution. Branch 181-make-netmanager-systemd-compatible is mostly meant to use in combination with node engine from 349-make-nodeengine-systemd-compatible which are both draft PRs I'm still working on :D 
Are you sure it received the subnetwork after all?

As @Mjaethers suggested if you don't need the overlay network support you can just avoid running the NetManger. 

An alternative approach is:

 Since it looks like everything is deployed on a single machine can you try 1-DOC setup? 

To do so just undeploy root and cluster and simply run the get-started script:

(optional) export `export OAKESTRA_BRANCH=develop` to use develop images and not the release ones.

Deploy a self-configured root and cluster on a single node. 
```
curl -sfL oakestra.io/getstarted.sh | sh - 
```

Then install the latest worker components (NodeEngine and NetManager) as usual and configure the NetManager as you did above.

If this works, then we know the issue was in the env configuration between cluster and root orchestrator and we know what to look at. 

Keep me posted ;)

**Comment by lucamarchiori** [comment]
Hi there,
to be sure of the results, i have booted up a Ubuntu VM and started from scratch with your suggestions.

VM Setup:
```
OS: Ubuntu 24.04.1 LTS x86_64 
Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-7.1) 
Kernel: 6.8.0-45-generic 
Packages: 782 (dpkg) 
Shell: bash 5.2.21 
Resolution: 1024x768 
Terminal: /dev/pts/0 
CPU: AMD Ryzen 5 5600G with Radeon Graphics (2) @ 3.892GHz 
GPU: 00:01.0 Red Hat, Inc. QXL paravirtual graphic card 
Memory: 231MiB / 3911MiB
```

Env variables:
```bash
export CLUSTER_NAME=TestingCluster
export SYSTEM_MANAGER_URL="192.168.1.95"
export CLUSTER_LOCATION="45.41133680404686,11.887593367138129,5"
export OAKESTRA_BRANCH=develop
```

Network config:
```
enp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 192.168.1.95  netmask 255.255.255.0  broadcast 192.168.1.255
inet6 2a01:e11:6007:5170:5054:ff:fe3e:3b42  prefixlen 64  scopeid 0x0<gl
```

I ran the `getstarted.sh` script and both the dashboard and APIs were accessible.

I installed the NetworkManager and the NodeEngine from the script `InstallOakestraWorker.sh `

Network Manager config in `/etc/netmanager/netcfg.json`
```
{
  "NodePublicAddress": "192.168.1.95",
  "NodePublicPort": "50103",
  "ClusterUrl": "0.0.0.0",
  "ClusterMqttPort": "10003"
}
```

I ran the NetManager
```
lucam@ubuntuserver:~/GS-ODOC$ sudo NetManager -p 6000
2024/10/18 07:44:49 {192.168.1.95 50103 0.0.0.0 10003}
2024/10/18 07:44:49 NetManager started. Waiting for registration.
```

I ran the NodeEngine and got an error:
```
lucam@ubuntuserver:~/GS-ODOC$ sudo NodeEngine -a 192.168.1.95
[sudo] password for lucam: 
INFO-2024/10/18 07:45:43 ContainersManagement.go:395: Clenaning up container: hw.hw.nx.nx.instance.0
ERROR-2024/10/18 07:45:43 ContainersManagement.go:398: Unable to fetch container task: no running task found: task hw.hw.nx.nx.instance.0 not found: not found
INFO-2024/10/18 07:45:44 NodeEngine.go:69: INIT: Starting handshake with cluster orhcestrator 192.168.1.95:10000
INFO-2024/10/18 07:45:44 NodeEngine.go:71: Node Statistics: 
__________________
INFO-2024/10/18 07:45:44 NodeEngine.go:72: CPU Cores: 2
INFO-2024/10/18 07:45:44 NodeEngine.go:73: CPU Usage: 1.590000
INFO-2024/10/18 07:45:44 NodeEngine.go:74: Mem Usage: 27.447226
INFO-2024/10/18 07:45:44 NodeEngine.go:75: GPU Driver: -
INFO-2024/10/18 07:45:44 NodeEngine.go:76: 
________________
ERROR-2024/10/18 07:45:44 ClusterManagerRequests.go:29: Handshake failed with error code 404
```

But if i run the NodeEngine with the additional flags then it starts correctly. I suggest to update the readme because from there it seems that the -a flag is the only one necessary to run the NodeEngine.
```
lucam@ubuntuserver:~/GS-ODOC$ sudo NodeEngine -a 192.168.1.95 -p 10100 -n 6000
INFO-2024/10/18 07:48:17 NodeEngine.go:69: INIT: Starting handshake with cluster orhcestrator 192.168.1.95:10100
INFO-2024/10/18 07:48:17 NodeEngine.go:71: Node Statistics: 
__________________
INFO-2024/10/18 07:48:17 NodeEngine.go:72: CPU Cores: 2
INFO-2024/10/18 07:48:17 NodeEngine.go:73: CPU Usage: 0.980000
INFO-2024/10/18 07:48:17 NodeEngine.go:74: Mem Usage: 27.612219
INFO-2024/10/18 07:48:17 NodeEngine.go:75: GPU Driver: -
INFO-2024/10/18 07:48:17 NodeEngine.go:76: 
________________
INFO-2024/10/18 07:48:17 NodeEngine.go:78: Got cluster response with MQTT port 10003 and node ID 671212c1180a08f241a4d387
INFO-2024/10/18 07:48:18 MqttClient.go:26: Connected to the MQTT broker
INFO-2024/10/18 07:48:18 MqttClient.go:36: Subscribed to topics 
INFO-2024/10/18 07:48:20 MqttClient.go:88: MQTT - publish to - jobs/resources - the payload - {"services":[]}
INFO-2024/10/18 07:48:20 MqttClient.go:88: MQTT - publish to - information - the payload - {"id":"","host":"","ip":"","port":"","system_info":null,"cpu":0.98,"free_cores":2,"architecture":"","memory":27.743554096055355,"memory_free_in_MB":2529,"disk_info":null,"network_info":null,"gpu_driver":"-","gpu_usage":0,"gpu_cores":0,"gpu_temp":0,"gpu_mem_used":0,"gpu_tot_mem":0,"technology":null,"Overlay":false,"LogDirectory":"","NetManagerPort":0}
INFO-2024/10/18 07:48:22 MqttClient.go:88: MQTT - publish to - jobs/resources - the payload - {"services":[]}
INFO-2024/10/18 07:48:22 MqttClient.go:88: MQTT - publish to - information - the payload - {"id":"","host":"","ip":"","port":"","system_info":null,"cpu":1,"free_cores":2,"architecture":"","memory":27.942803838378993,"memory_free_in_MB":2521,"disk_info":null,"network_info":null,"gpu_driver":"-","gpu_usage":0,"gpu_cores":0,"gpu_temp":0,"gpu_mem_used":0,"gpu_tot_mem":0,"technology":null,"Overlay":false,"LogDirectory":"","NetManagerPort":0}
INFO-2024/10/18 07:48:24 MqttClient.go:88: MQTT - publish to - jobs/resources - the payload - {"services":[]}
INFO-2024/10/18 07:48:24 MqttClient.go:88: MQTT - publish to - information - the payload - {"id":"","host":"","ip":"","port":"","system_info":null,"cpu":1,"free_cores":2,"architecture":"","memory":27.942304465591217,"memory_free_in_MB":2521,"disk_info":null,"network_info":null,"gpu_driver":"-","gpu_usage":0,"gpu_cores":0,"gpu_temp":0,"gpu_mem_used":0,"gpu_tot_mem":0,"technology":null,"Overlay":false,"LogDirectory":"","NetManagerPort":0}
INFO-2024/10/18 07:48:26 MqttClient.go:88: MQTT - publish to - jobs/resources - the payload - {"services":[]}
INFO-2024/10/18 07:48:26 MqttClient.go:88: MQTT - publish to - information - the payload - {"id":"","host":"","ip":"","port":"","system_info":null,"cpu":0.98,"free_cores":2,"architecture":"","memory":27.942104716476106,"memory_free_in_MB":2521,"disk_info":null,"network_info":null,"gpu_driver":"-","gpu_usage":0,"gpu_cores":0,"gpu_temp":0,"gpu_mem_used":0,"gpu_tot_mem":0,"technology":null,"Overlay":false,"LogDirectory":"","NetManagerPort":0}
```

The deployment of ngnix on the cluster is successful.

Now, since i'd like to start exploring the source code i wanted to try running the same setup without `InstallOakestraWorker.sh` and `getstarted.sh` scripts. Instead, by running the containers from the repos.

I cloned both the repos of oakestra and oakestra-net (both branches on develop) and stopped and removed all docker containers and images. Then followed the readme for RootOrchestrator and ClusterOrchestrator

- RootOrcehstrator: pulls and builds successfully.
- ClusterOrcehstrator: pulls and builds successfully.

The NodeEngine builds successfully and both the build and install scripts work. However, if i start it without NetworkManager i get:
```
lucam@ubuntuserver:~/oak/oak-src/go_node_engine/build$ sudo NodeEngine -p 10100 -n 6000 -a 192.168.1.95
INFO-2024/10/18 08:25:46 root.go:96: INIT: Starting handshake with cluster orchestrator 192.168.1.95:10100
INFO-2024/10/18 08:25:46 root.go:98: Node Statistics: 
__________________
INFO-2024/10/18 08:25:46 root.go:99: CPU Cores: 2
INFO-2024/10/18 08:25:46 root.go:100: CPU Usage: 0.790000
INFO-2024/10/18 08:25:46 root.go:101: Mem Usage: 33.980321
INFO-2024/10/18 08:25:46 root.go:102: GPU Driver: -
INFO-2024/10/18 08:25:46 root.go:103: 
________________
INFO-2024/10/18 08:25:46 root.go:105: Got cluster response with MQTT port 10003 and node ID 67121b30e5d714c71153eb5c
ERROR-2024/10/18 08:25:46 root.go:71: Unable to register to NetManager: Post "http://localhost:6000/register": dial tcp 127.0.0.1:6000: connect: connection refused
```

Instead, if i start both the NodeEngine and the NetworkManager they work and i am able to deploy services such as Ngnix on the cluster.

So with a clear setup i am not able to replicate the error that i got when i opened this issue. Thanks for your help.

**Comment by Mjaethers** [comment]
Thank you for being so thorough! So it seems it had to do with the flags for the NodeEngine, but this will be simplified when the demonized branch is merged anyway.
